//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Maio11_Best.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class aluga
    {
        public int idal { get; set; }
        public Nullable<int> idcli { get; set; }
        public Nullable<int> idcar { get; set; }
        public Nullable<decimal> tempo { get; set; }
        public Nullable<decimal> custo { get; set; }
        public Nullable<System.DateTime> dataaluguer { get; set; }
    }
}
