//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Maio11_Best.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class carro
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public carro()
        {
            this.alugueres = new HashSet<aluguere>();
        }
    
        public int idcar { get; set; }
        public string modelo { get; set; }
        public Nullable<decimal> phora { get; set; }
        public string marca { get; set; }
        public string fotopath { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<aluguere> alugueres { get; set; }
        public virtual marca marca1 { get; set; }
    }
}
