//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Maio11_Best.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class historico
    {
        public int idcli { get; set; }
        public string graca { get; set; }
        public string categoria { get; set; }
        public Nullable<System.DateTime> datanasc { get; set; }
        public Nullable<decimal> idade { get; set; }
        public Nullable<int> boss { get; set; }
    }
}
