//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Maio11_Best.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class bdbestEntities : DbContext
    {
        public bdbestEntities()
            : base("name=bdbestEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<aluguere> alugueres { get; set; }
        public virtual DbSet<carro> carros { get; set; }
        public virtual DbSet<cliente> clientes { get; set; }
        public virtual DbSet<marca> marcas { get; set; }
        public virtual DbSet<aluga> alugas { get; set; }
        public virtual DbSet<historico> historicoes { get; set; }
        public virtual DbSet<nova> novae { get; set; }
        public virtual DbSet<v_carros> v_carros { get; set; }
    }
}
