//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System.ComponentModel.DataAnnotations;
namespace Maio11_Best.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Team
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Team()
        {
            this.players = new HashSet<player>();
            this.trainers = new HashSet<trainer>();
        }
    
        public int team_id { get; set; }
        [Required(ErrorMessage = "Name is Required")]
        public string team_name { get; set; }

        [Required(ErrorMessage = "Year is Required")]
        [Range(1800, 2024, ErrorMessage = "Foundation year must be between 1800 and 2024")]
        public Nullable<int> foundation_year { get; set; }

        [Required(ErrorMessage = "Country is Required")]
        public string country { get; set; }
        public string photo_path { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<player> players { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<trainer> trainers { get; set; }
    }
}
