//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Maio11_Best.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class trainer
    {
        public int trainer_id { get; set; }
        public string trainer_name { get; set; }
        public string coaching_license { get; set; }
        public Nullable<int> team_id { get; set; }
    
        public virtual Team Team { get; set; }
    }
}
